global using BasicGameFrameworkLibrary.Core.BasicGameDataClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using static CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using CommonBasicLibraries.CollectionClasses;
global using fs = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.FileHelpers;
global using js = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.SystemTextJsonStrings; //just in case i need those 2.
global using BasicGameFrameworkLibrary.Core.CommonInterfaces;
global using Countdown.Core.Data;
global using BasicGameFrameworkLibrary.Core.BasicEventModels;
global using BasicGameFrameworkLibrary.Core.DIContainers;
global using MessengingHelpers;
global using CommonBasicLibraries.BasicUIProcesses;
global using BasicGameFrameworkLibrary.Core.CommandClasses;
global using BasicGameFrameworkLibrary.Core.ViewModels;
global using BasicGameFrameworkLibrary.Core.ViewModelInterfaces;
global using MVVMFramework.ViewModels;
global using Countdown.Core.Logic;
global using BasicGameFrameworkLibrary.Core.MiscProcesses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.MapHelpers;
global using BasicGameFrameworkLibrary.Core.Attributes;
global using BasicGameFrameworkLibrary.Blazor.Bootstrappers;
global using Countdown.Core.ViewModels;
global using aa = BasicGameFrameworkLibrary.Core.DIContainers.Helpers;
global using System;
global using System.Linq;
global using System.Threading.Tasks;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.GameContainers;
global using BasicGameFrameworkLibrary.Core.TestUtilities;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.RandomGenerator;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.BasicPlayerClasses;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.SavedGameClasses;
global using BasicGameFrameworkLibrary.Core.GeneratorHelpers;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.BasicGameClasses;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.InterfaceMessages;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.MainViewModels;
global using BasicGameFrameworkLibrary.Blazor.Shells;
global using Microsoft.AspNetCore.Components;
global using BasicGameFrameworkLibrary.Blazor.Extensions;
global using BasicGameFrameworkLibrary.Blazor.Helpers;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.InterfaceModels;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.Extensions;
global using BasicGameFrameworkLibrary.Core.Dice;
global using BasicGameFrameworkLibrary.Core.ScoreBoardClassesCP;
global using System.Drawing;
global using Countdown.Core.Graphics;
global using BasicGameFrameworkLibrary.Blazor.GameGraphics.GamePieces;
global using cs = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;