global using BasicGameFrameworkLibrary.Core.BasicGameDataClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using static CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using CommonBasicLibraries.CollectionClasses;
global using fs = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.FileHelpers;
global using js = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.SystemTextJsonStrings; //just in case i need those 2.
global using BasicGameFrameworkLibrary.Core.CommonInterfaces;
global using PyramidSolitaire.Core.Data;
global using BasicGameFrameworkLibrary.Core.BasicEventModels;
global using BasicGameFrameworkLibrary.Core.DIContainers;
global using MessengingHelpers;
global using CommonBasicLibraries.BasicUIProcesses;
global using BasicGameFrameworkLibrary.Core.CommandClasses;
global using BasicGameFrameworkLibrary.Core.ViewModels;
global using BasicGameFrameworkLibrary.Core.ViewModelInterfaces;
global using MVVMFramework.ViewModels;
global using PyramidSolitaire.Core.Logic;
global using BasicGameFrameworkLibrary.Core.MiscProcesses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.MapHelpers;
global using BasicGameFrameworkLibrary.Core.Attributes;
global using BasicGameFrameworkLibrary.Blazor.Bootstrappers;
global using PyramidSolitaire.Core.ViewModels;
global using aa = BasicGameFrameworkLibrary.Core.DIContainers.Helpers;
global using System;
global using System.Linq;
global using System.Threading.Tasks;
global using BasicGameFrameworkLibrary.Core.RegularDeckOfCards;
global using BasicGameFrameworkLibrary.Core.BasicDrawables.Interfaces;
global using BasicGameFrameworkLibrary.Core.DrawableListsObservable;
global using BasicGameFrameworkLibrary.Core.Extensions;
global using BasicGameFrameworkLibrary.Core.BasicDrawables.Dictionary;
global using BasicGameFrameworkLibrary.Core.SolitaireClasses.Cards;
global using BasicGameFrameworkLibrary.Core.SolitaireClasses.TriangleClasses;
global using PyramidSolitaire.Core.EventModels;
global using BasicGameFrameworkLibrary.Core.GeneratorHelpers;
global using System.Collections.Generic;
