global using BasicGameFrameworkLibrary.Core.BasicGameDataClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using static CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using CommonBasicLibraries.CollectionClasses;
global using fs = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.FileHelpers;
global using js = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.SystemTextJsonStrings; //just in case i need those 2.
global using BasicGameFrameworkLibrary.Core.CommonInterfaces;
global using CrazyEights.Core.Data;
global using BasicGameFrameworkLibrary.Core.BasicEventModels;
global using BasicGameFrameworkLibrary.Core.DIContainers;
global using MessengingHelpers;
global using CommonBasicLibraries.BasicUIProcesses;
global using BasicGameFrameworkLibrary.Core.CommandClasses;
global using BasicGameFrameworkLibrary.Core.ViewModels;
global using BasicGameFrameworkLibrary.Core.ViewModelInterfaces;
global using MVVMFramework.ViewModels;
global using CrazyEights.Core.Logic;
global using BasicGameFrameworkLibrary.Core.MiscProcesses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.MapHelpers;
global using BasicGameFrameworkLibrary.Core.Attributes;
global using BasicGameFrameworkLibrary.Blazor.Bootstrappers;
global using CrazyEights.Core.ViewModels;
global using aa = BasicGameFrameworkLibrary.Core.DIContainers.Helpers;
global using System;
global using System.Linq;
global using System.Threading.Tasks;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.GameContainers;
global using BasicGameFrameworkLibrary.Core.TestUtilities;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.RandomGenerator;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.BasicPlayerClasses;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.SavedGameClasses;
global using BasicGameFrameworkLibrary.Core.GeneratorHelpers;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.BasicGameClasses;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.InterfaceMessages;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.MainViewModels;
global using BasicGameFrameworkLibrary.Blazor.Shells;
global using Microsoft.AspNetCore.Components;
global using BasicGameFrameworkLibrary.Blazor.Extensions;
global using BasicGameFrameworkLibrary.Blazor.Helpers;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.InterfaceModels;
global using BasicGameFrameworkLibrary.Core.MultiplayerClasses.Extensions;
global using BasicGameFrameworkLibrary.Core.Dice;
global using BasicGameFrameworkLibrary.Core.ScoreBoardClassesCP;
global using SvgHelper.Blazor.Logic;
global using SvgHelper.Blazor.Logic.Classes.SubClasses;
global using Microsoft.AspNetCore.Components.Rendering;
global using SvgHelper.Blazor.Logic.Classes.Interfaces;
global using BasicGameFrameworkLibrary.Blazor.BasicControls.GameBoards;
global using System.Drawing;
global using System.Collections.Generic;
global using BasicGameFrameworkLibrary.Core.BasicDrawables.Dictionary;
global using BasicGameFrameworkLibrary.Core.BasicDrawables.Interfaces;
global using BasicGameFrameworkLibrary.Core.RegularDeckOfCards;
global using BasicGameFrameworkLibrary.Core.DrawableListsObservable;
global using BasicGameFrameworkLibrary.Core.Extensions;
global using BasicGameFrameworkLibrary.Core.ChooserClasses;
global using mm = BasicGameFrameworkLibrary.Core.Extensions.CommonMessageStrings;
global using co = CrazyEights.Core.Logic.CrazyEightsComputerAI;