global using BasicGameFrameworkLibrary.Core.BasicGameDataClasses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using static CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using CommonBasicLibraries.CollectionClasses;
global using fs = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.FileHelpers;
global using js = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.SystemTextJsonStrings; //just in case i need those 2.
global using BasicGameFrameworkLibrary.Core.CommonInterfaces;
global using SolitaireBoardGame.Core.Data;
global using BasicGameFrameworkLibrary.Core.BasicEventModels;
global using BasicGameFrameworkLibrary.Core.DIContainers;
global using MessengingHelpers;
global using CommonBasicLibraries.BasicUIProcesses;
global using BasicGameFrameworkLibrary.Core.CommandClasses;
global using BasicGameFrameworkLibrary.Core.ViewModels;
global using BasicGameFrameworkLibrary.Core.ViewModelInterfaces;
global using MVVMFramework.ViewModels;
global using SolitaireBoardGame.Core.Logic;
global using BasicGameFrameworkLibrary.Core.MiscProcesses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.MapHelpers;
global using BasicGameFrameworkLibrary.Core.Attributes;
global using BasicGameFrameworkLibrary.Blazor.Bootstrappers;
global using SolitaireBoardGame.Core.ViewModels;
global using cs = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using System.Collections;
global using BasicGameFrameworkLibrary.Core.GameBoardCollections;
global using BasicGameFrameworkLibrary.Core.GeneratorHelpers;
global using aa = BasicGameFrameworkLibrary.Core.DIContainers.Helpers;
global using BasicGameFrameworkLibrary.Blazor.BasicControls.GameBoards;
